[package]
name = "example_rust"
version = "0.1.0"
authors = ["Plugin Author <example@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
path = "source/plugin_example.rs"

[dependencies]
hex = { path = "./lib/libimhex-rs" }

[profile.release]
lto = true